// frontend/app/pages/movimentacoes.vue
<script setup lang="ts">
import type { Movimentacao } from "~/types";
definePageMeta({ titulo: "Movimentações" });

const { data: movimentacoes, pending, error } = useLazyFetch<Movimentacao[]>("/api/movimentacoes");
</script>

<template>
    <div class="flex flex-col gap-4">
        <div v-if="pending" class="text-tx-soft text-[13px] px-4">Carregando movimentações...</div>
        <div v-else-if="error" class="text-tx-soft text-[13px] px-4">Erro ao carregar movimentações.</div>

        <div v-else-if="movimentacoes" class="tbl-wrap">
            <div class="toolbar">
                <div class="busca">
                    <Icon name="lucide:search" class="w-[13px] h-[13px] text-tx-soft flex-shrink-0" />
                    <input type="text" placeholder="Buscar produto, SKU..." />
                </div>

                <select class="filtro-sel">
                    <option value="">Todos os tipos</option>
                    <option value="entrada">Entrada</option>
                    <option value="saida">Saída</option>
                </select>

                <span class="flex-1" />

                <button class="botao botao-primario text-[13px]">
                    <Icon name="lucide:plus" class="w-[13px] h-[13px]" />
                    Nova Movimentação
                </button>
            </div>

            <table class="w-full border-collapse">
                <thead>
                    <tr>
                        <th class="col-th">Tipo</th>
                        <th class="col-th">Produto</th>
                        <th class="col-th">SKU</th>
                        <th class="col-th">Qtd</th>
                        <th class="col-th">Responsável</th>
                        <th class="col-th">Criado em</th>
                    </tr>
                </thead>

                <tbody>
                    <tr v-for="m in movimentacoes" :key="m.id" class="linha">
                        <td class="col-td">
                            <Etiqueta
                                :status="m.tipo === 'entrada' ? 'ok' : 'info'"
                                :rotulo="m.tipo === 'entrada' ? 'Entrada' : 'Saída'"
                            />
                        </td>
                        <td class="col-td font-medium">{{ m.produto }}</td>
                        <td class="col-td text-tx-mid">{{ m.sku }}</td>
                        <td class="col-td font-medium">{{ m.quantidade }}</td>
                        <td class="col-td text-tx-mid">{{ m.responsavel }}</td>
                        <td class="col-td text-tx-soft">{{ formatarDataHora(m.data) }}</td>
                    </tr>
                </tbody>
            </table>

            <div class="paginacao">
                <span class="pag-info">{{ movimentacoes.length }} movimentações</span>
            </div>
        </div>
    </div>
</template>

// src/pages/Movimentacoes/index.tsx
import { Plus, Search } from "lucide-react";
import { useState } from "react";
import { Button } from "../../components/ui/Button";
import { Input } from "../../components/ui/Input";
import { PageHeader } from "../../components/ui/PageHeader";
import { Select } from "../../components/ui/Select";
import { useMovimentacoes } from "../../hooks/useMovimentacoes";
import { formatDate } from "../../utils/formatters";
import { MovimentacaoFormModal } from "./MovimentacaoFormModal";
import styles from "./styles.module.css";

export function Movimentacoes() {
    const {
        movimentacoes,
        produtos,
        loading,
        busca,
        setBusca,
        tipoFiltro,
        setTipoFiltro,
        produtoFiltro,
        setProdutoFiltro,
        recarregar,
    } = useMovimentacoes();

    const [isModalOpen, setIsModalOpen] = useState(false);

    const handleSuccess = () => {
        setIsModalOpen(false);
        recarregar();
    };

    return (
        <div className="page-container">
            <PageHeader title="Histórico de Movimentações" subtitle="Auditoria de entradas e saídas de estoque.">
                <Button onClick={() => setIsModalOpen(true)}>
                    <Plus size={18} style={{ marginRight: 8 }} />
                    Nova Movimentação
                </Button>
            </PageHeader>

            <div className="filter-grid">
                <div className="search-wrapper">
                    <Search size={18} className="search-icon" />
                    <Input
                        placeholder="Buscar por produto ou SKU..."
                        value={busca}
                        onChange={(e) => setBusca(e.target.value)}
                        className="search-input"
                    />
                </div>
                <div>
                    <Select value={produtoFiltro} onChange={(e) => setProdutoFiltro(e.target.value)}>
                        <option value="">Todos os produtos</option>
                        {produtos.map((p) => (
                            <option key={p.id} value={p.id}>
                                {p.nome}
                            </option>
                        ))}
                    </Select>
                </div>
                <div>
                    <Select value={tipoFiltro} onChange={(e) => setTipoFiltro(e.target.value)}>
                        <option value="">Todos os tipos</option>
                        <option value="entrada">Entradas</option>
                        <option value="saida">Saídas</option>
                    </Select>
                </div>
            </div>

            <div className="table-container">
                {loading ? (
                    <div className="loading-state">Carregando histórico...</div>
                ) : movimentacoes.length === 0 ? (
                    <div className="empty-state">Nenhuma movimentação encontrada.</div>
                ) : (
                    <table className="data-table">
                        <thead>
                            <tr>
                                <th>Tipo</th>
                                <th>Produto</th>
                                <th className="text-right">Qtd.</th>
                                <th>Responsável</th>
                                <th>Motivo</th>
                                <th>Data e Hora</th>
                            </tr>
                        </thead>
                        <tbody>
                            {movimentacoes.map((mov) => (
                                <tr key={mov.id}>
                                    <td>
                                        <div className={styles.flex_center_gap8}>
                                            <div
                                                style={{
                                                    width: "8px",
                                                    height: "8px",
                                                    borderRadius: "50%",
                                                    backgroundColor:
                                                        mov.tipo === "entrada"
                                                            ? "var(--color-success-text)"
                                                            : "var(--color-danger-text)",
                                                }}
                                            ></div>
                                            <span className={styles.text_capitalize_fw500}>{mov.tipo}</span>
                                        </div>
                                    </td>
                                    <td className="fw500">{mov.produtos?.nome || "-"}</td>
                                    <td
                                        className={`${mov.tipo === "entrada" ? styles.text_success : styles.text_danger} text-right fw600`}
                                    >
                                        {mov.tipo === "entrada" ? "+" : "-"}
                                        {mov.quantidade}
                                    </td>
                                    <td>{mov.responsavel}</td>
                                    <td className="text-secondary">{mov.motivo || "-"}</td>
                                    <td className="text-secondary">{formatDate(mov.criada_em)}</td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                )}
            </div>

            <MovimentacaoFormModal
                isOpen={isModalOpen}
                onClose={() => setIsModalOpen(false)}
                produtos={produtos}
                onSuccess={handleSuccess}
            />
        </div>
    );
}
